<Project>
  <!-- Global project and StyleCop Analyzers configuration -->
  <PropertyGroup>
    <Version>1.0.0</Version>
    <Authors>US Xpress Engineering</Authors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;SA1600</NoWarn>
  </PropertyGroup>

  <!-- Style -->
  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="all" />
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)\style\stylecop.json" Link="stylecop.json" Visible="false"/>
  </ItemGroup>
</Project>
