---
services:
  app:
    build:
      context: .
      args:
        - GITHUB_USER=$GITHUB_USER
        - GITHUB_TOKEN=$GITHUB_TOKEN
    ports:
      - 8080:8080
    environment:
      APPLICATION__ENVIRONMENT: testing
      APPLICATION__PROJECT: python-demo-poc
      APPLICATION__GROUP: demo
      REVISION: 0.10.0
    env_file:
      - .env
    stop_grace_period: 2s
