[logging]
    default = FILE:/var/log/krb5libs.log
    kdc = FILE:/var/log/krb5kdc.log
    admin_server = FILE:/var/log/kadmind.log

[libdefaults]
    default_realm = USXPRESS.COM

[realms]
    USXPRESS.COM = {
        default_domain = usxpress.com

        kdc = USXD1VMDC1.usxpress.com
        kdc = USXD1VMDC2.usxpress.com
        kdc = USXD1VMDC3.usxpress.com

        kdc = USXD2VMDC1.usxpress.com
        kdc = USXD2VMDC2.usxpress.com
    }

[domain_realm]
    .usxpress.com = USXPRESS.COM
    usxpress.com = USXPRESS.COM
