<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>io-elsa-api-5a4b6c8d-0e9f-4a2b-8c7d-6e5f4a3b2c1d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Client" />
    <PackageReference Include="Microsoft.Identity.Web" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Asp.Versioning.Http" />
    <PackageReference Include="NSwag.AspNetCore" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="USXpress.Monitoring" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Core\Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
