---
# yamllint disable rule:line-length
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MASTER_BRANCH: master

jobs:
  build:
    name: Build Image and Push to Octo
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Artifact 📦
        uses: variant-inc/actions-dotnet@v2
        with:
          ecr_repository: usxpress/io-platform
          dotnet-version: 8.x

      - name: Release 🛸
        uses: variant-inc/actions-octopus@v3
        with:
          deploy_yaml_dir: .octopus/deploy